### ISSUE TITLE
Got it installed. Trying it out. Ran into a problem.

### ISSUE THREAD

**Issue by herbsmn** [kylewm/KnownTwitterBackfill#1]
I typed this in to my terminal:
curl -x POST https://freekurt.com/twitter/backfill/cron

And I got this:
curl: (7) Failed to connect to POST port 1080: Connection timed out

Any suggestions? This sounds like an awesome plugin!

**Comment by karadaisy** [comment]
try `curl -X POST https://freekurt.com/twitter/backfill/cron` (capital X)

**Comment by herbsmn** [comment]
i'm not exactly sure what is supposed to happen. a long document is displayed after I type enter on that command. it starts with this: 

```
<!DOCTYPE html>
<html lang="en">
<head>


<meta charset="utf-8">
<title>Not found!</title>

```

**Comment by herbsmn** [comment]
actually, twitter backfill doesn't seem to enable after i hit enable in my plugins tab in Known. i'm gonna try to figure out what is going on

**Comment by herbsmn** [comment]
ok, I renamed the app TwitterBackfill. I was using the name of this github repo before, KnownTwitterBackfill and it wasn't working. After renaming it, I was able to enable it in Known and then when I ran the command it seemed to work!

**Comment by herbsmn** [comment]
thanks so much for making this app and allowing me to PESOS my twitter data. you can close this issue.

**Comment by karadaisy** [comment]
Nice! (And hmm, that naming thing is a problem a few people have had ... it would be nice if Known gave you some kind of warning)

**Comment by chrisaldrich** [comment]
<a href="https://github.com/kylewm/KnownTwitterBackfill/issues/1" class="u-in-reply-to"></a>I've run into Known's naming convention issues with contributed plugins several times. Experience always tells me to rename, but it would be nice if it threw an error.
